CREATE TRIGGER ONE_PERSON_ONE_PROFILE ON MEMBER_PROFILE
INSTEAD OF INSERT
AS
DECLARE @memberID int
DECLARE @ProfileID int
SELECT @ProfileID=inserted.ProfileID, @memberID=inserted.MemberID
FROM inserted
WHERE NOT EXISTS( SELECT MEMBER_PROFILE.ProfileID
			FROM MEMBER_PROFILE
			WHERE inserted.ProfileID=MEMBER_PROFILE.ProfileID);

INSERT INTO MEMBER_PROFILE(MemberID,ProfileID) VALUES(@memberID,@ProfileID);
