CREATE TRIGGER SAME_EMAILS ON PROFILE_MAILS
INSTEAD OF INSERT
AS
DECLARE @ProfileID int
DECLARE @Mail varchar(50)
SELECT @ProfileID=inserted.ProfileID, @Mail=inserted.Mail
FROM inserted
WHERE NOT EXISTS( SELECT PROFILE_MAILS.Mail
			FROM PROFILE_MAILS
			WHERE inserted.mail=PROFILE_MAILS.Mail);

INSERT INTO PROFILE_MAILS(ProfileID,mail) VALUES(@ProfileID,@Mail);